//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.WLIMS.Web.WCFService.Delivery {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.Delivery.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/Add", ReplyAction="http://tempuri.org/IOrderService/AddResponse")]
        bool Add(SOA.WLIMS.Models.OrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/Modify", ReplyAction="http://tempuri.org/IOrderService/ModifyResponse")]
        bool Modify(SOA.WLIMS.Models.OrderModel order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/Delete", ReplyAction="http://tempuri.org/IOrderService/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/Get", ReplyAction="http://tempuri.org/IOrderService/GetResponse")]
        SOA.WLIMS.Models.OrderModel Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/Query", ReplyAction="http://tempuri.org/IOrderService/QueryResponse")]
        SOA.WLIMS.Models.OrderModel[] Query(SOA.WLIMS.Models.QueryParam para);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : SOA.WLIMS.Web.WCFService.Delivery.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<SOA.WLIMS.Web.WCFService.Delivery.IOrderService>, SOA.WLIMS.Web.WCFService.Delivery.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(SOA.WLIMS.Models.OrderModel order) {
            return base.Channel.Add(order);
        }
        
        public bool Modify(SOA.WLIMS.Models.OrderModel order) {
            return base.Channel.Modify(order);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public SOA.WLIMS.Models.OrderModel Get(int id) {
            return base.Channel.Get(id);
        }
        
        public SOA.WLIMS.Models.OrderModel[] Query(SOA.WLIMS.Models.QueryParam para) {
            return base.Channel.Query(para);
        }
    }
}
