//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SOA.WLIMS.DAL
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class SOAWLDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“SOAWLDBEntities”部分中的连接字符串初始化新 SOAWLDBEntities 对象。
        /// </summary>
        public SOAWLDBEntities() : base("name=SOAWLDBEntities", "SOAWLDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SOAWLDBEntities 对象。
        /// </summary>
        public SOAWLDBEntities(string connectionString) : base(connectionString, "SOAWLDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SOAWLDBEntities 对象。
        /// </summary>
        public SOAWLDBEntities(EntityConnection connection) : base(connection, "SOAWLDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<DeliveryInfo> DeliveryInfo
        {
            get
            {
                if ((_DeliveryInfo == null))
                {
                    _DeliveryInfo = base.CreateObjectSet<DeliveryInfo>("DeliveryInfo");
                }
                return _DeliveryInfo;
            }
        }
        private ObjectSet<DeliveryInfo> _DeliveryInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Order> Order
        {
            get
            {
                if ((_Order == null))
                {
                    _Order = base.CreateObjectSet<Order>("Order");
                }
                return _Order;
            }
        }
        private ObjectSet<Order> _Order;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Storehouse> Storehouse
        {
            get
            {
                if ((_Storehouse == null))
                {
                    _Storehouse = base.CreateObjectSet<Storehouse>("Storehouse");
                }
                return _Storehouse;
            }
        }
        private ObjectSet<Storehouse> _Storehouse;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Vehicle> Vehicle
        {
            get
            {
                if ((_Vehicle == null))
                {
                    _Vehicle = base.CreateObjectSet<Vehicle>("Vehicle");
                }
                return _Vehicle;
            }
        }
        private ObjectSet<Vehicle> _Vehicle;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MD_Message> MD_Message
        {
            get
            {
                if ((_MD_Message == null))
                {
                    _MD_Message = base.CreateObjectSet<MD_Message>("MD_Message");
                }
                return _MD_Message;
            }
        }
        private ObjectSet<MD_Message> _MD_Message;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MD_MessageLog> MD_MessageLog
        {
            get
            {
                if ((_MD_MessageLog == null))
                {
                    _MD_MessageLog = base.CreateObjectSet<MD_MessageLog>("MD_MessageLog");
                }
                return _MD_MessageLog;
            }
        }
        private ObjectSet<MD_MessageLog> _MD_MessageLog;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 DeliveryInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDeliveryInfo(DeliveryInfo deliveryInfo)
        {
            base.AddObject("DeliveryInfo", deliveryInfo);
        }
    
        /// <summary>
        /// 用于向 Order EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrder(Order order)
        {
            base.AddObject("Order", order);
        }
    
        /// <summary>
        /// 用于向 Storehouse EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStorehouse(Storehouse storehouse)
        {
            base.AddObject("Storehouse", storehouse);
        }
    
        /// <summary>
        /// 用于向 User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// 用于向 Vehicle EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToVehicle(Vehicle vehicle)
        {
            base.AddObject("Vehicle", vehicle);
        }
    
        /// <summary>
        /// 用于向 MD_Message EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMD_Message(MD_Message mD_Message)
        {
            base.AddObject("MD_Message", mD_Message);
        }
    
        /// <summary>
        /// 用于向 MD_MessageLog EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMD_MessageLog(MD_MessageLog mD_MessageLog)
        {
            base.AddObject("MD_MessageLog", mD_MessageLog);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="DeliveryInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeliveryInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 DeliveryInfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="orderCode">OrderCode 属性的初始值。</param>
        /// <param name="handleTime">HandleTime 属性的初始值。</param>
        /// <param name="handleStatus">HandleStatus 属性的初始值。</param>
        public static DeliveryInfo CreateDeliveryInfo(global::System.Int64 id, global::System.String orderCode, global::System.DateTime handleTime, global::System.String handleStatus)
        {
            DeliveryInfo deliveryInfo = new DeliveryInfo();
            deliveryInfo.ID = id;
            deliveryInfo.OrderCode = orderCode;
            deliveryInfo.HandleTime = handleTime;
            deliveryInfo.HandleStatus = handleStatus;
            return deliveryInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderCode
        {
            get
            {
                return _OrderCode;
            }
            set
            {
                OnOrderCodeChanging(value);
                ReportPropertyChanging("OrderCode");
                _OrderCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderCode");
                OnOrderCodeChanged();
            }
        }
        private global::System.String _OrderCode;
        partial void OnOrderCodeChanging(global::System.String value);
        partial void OnOrderCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> StorehouseID
        {
            get
            {
                return _StorehouseID;
            }
            set
            {
                OnStorehouseIDChanging(value);
                ReportPropertyChanging("StorehouseID");
                _StorehouseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StorehouseID");
                OnStorehouseIDChanged();
            }
        }
        private Nullable<global::System.Int64> _StorehouseID;
        partial void OnStorehouseIDChanging(Nullable<global::System.Int64> value);
        partial void OnStorehouseIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> VehicleID
        {
            get
            {
                return _VehicleID;
            }
            set
            {
                OnVehicleIDChanging(value);
                ReportPropertyChanging("VehicleID");
                _VehicleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VehicleID");
                OnVehicleIDChanged();
            }
        }
        private Nullable<global::System.Int64> _VehicleID;
        partial void OnVehicleIDChanging(Nullable<global::System.Int64> value);
        partial void OnVehicleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HandleTime
        {
            get
            {
                return _HandleTime;
            }
            set
            {
                OnHandleTimeChanging(value);
                ReportPropertyChanging("HandleTime");
                _HandleTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HandleTime");
                OnHandleTimeChanged();
            }
        }
        private global::System.DateTime _HandleTime;
        partial void OnHandleTimeChanging(global::System.DateTime value);
        partial void OnHandleTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HandleStatus
        {
            get
            {
                return _HandleStatus;
            }
            set
            {
                OnHandleStatusChanging(value);
                ReportPropertyChanging("HandleStatus");
                _HandleStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HandleStatus");
                OnHandleStatusChanged();
            }
        }
        private global::System.String _HandleStatus;
        partial void OnHandleStatusChanging(global::System.String value);
        partial void OnHandleStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HandleMessage
        {
            get
            {
                return _HandleMessage;
            }
            set
            {
                OnHandleMessageChanging(value);
                ReportPropertyChanging("HandleMessage");
                _HandleMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HandleMessage");
                OnHandleMessageChanged();
            }
        }
        private global::System.String _HandleMessage;
        partial void OnHandleMessageChanging(global::System.String value);
        partial void OnHandleMessageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="MD_Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MD_Message : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MD_Message 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static MD_Message CreateMD_Message(global::System.Guid id)
        {
            MD_Message mD_Message = new MD_Message();
            mD_Message.ID = id;
            return mD_Message;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> SourceID
        {
            get
            {
                return _SourceID;
            }
            set
            {
                OnSourceIDChanging(value);
                ReportPropertyChanging("SourceID");
                _SourceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceID");
                OnSourceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _SourceID;
        partial void OnSourceIDChanging(Nullable<global::System.Guid> value);
        partial void OnSourceIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mails
        {
            get
            {
                return _Mails;
            }
            set
            {
                OnMailsChanging(value);
                ReportPropertyChanging("Mails");
                _Mails = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mails");
                OnMailsChanged();
            }
        }
        private global::System.String _Mails;
        partial void OnMailsChanging(global::System.String value);
        partial void OnMailsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobiles
        {
            get
            {
                return _Mobiles;
            }
            set
            {
                OnMobilesChanging(value);
                ReportPropertyChanging("Mobiles");
                _Mobiles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobiles");
                OnMobilesChanged();
            }
        }
        private global::System.String _Mobiles;
        partial void OnMobilesChanging(global::System.String value);
        partial void OnMobilesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Receiver
        {
            get
            {
                return _Receiver;
            }
            set
            {
                OnReceiverChanging(value);
                ReportPropertyChanging("Receiver");
                _Receiver = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Receiver");
                OnReceiverChanged();
            }
        }
        private global::System.String _Receiver;
        partial void OnReceiverChanging(global::System.String value);
        partial void OnReceiverChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MsgDate
        {
            get
            {
                return _MsgDate;
            }
            set
            {
                OnMsgDateChanging(value);
                ReportPropertyChanging("MsgDate");
                _MsgDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MsgDate");
                OnMsgDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MsgDate;
        partial void OnMsgDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMsgDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSended
        {
            get
            {
                return _IsSended;
            }
            set
            {
                OnIsSendedChanging(value);
                ReportPropertyChanging("IsSended");
                _IsSended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSended");
                OnIsSendedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSended;
        partial void OnIsSendedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSendedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="MD_MessageLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MD_MessageLog : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MD_MessageLog 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static MD_MessageLog CreateMD_MessageLog(global::System.Guid id)
        {
            MD_MessageLog mD_MessageLog = new MD_MessageLog();
            mD_MessageLog.ID = id;
            return mD_MessageLog;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private Nullable<global::System.Guid> _MessageID;
        partial void OnMessageIDChanging(Nullable<global::System.Guid> value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SendTime
        {
            get
            {
                return _SendTime;
            }
            set
            {
                OnSendTimeChanging(value);
                ReportPropertyChanging("SendTime");
                _SendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendTime");
                OnSendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _SendTime;
        partial void OnSendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSendTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SendType
        {
            get
            {
                return _SendType;
            }
            set
            {
                OnSendTypeChanging(value);
                ReportPropertyChanging("SendType");
                _SendType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SendType");
                OnSendTypeChanged();
            }
        }
        private global::System.String _SendType;
        partial void OnSendTypeChanging(global::System.String value);
        partial void OnSendTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSuccess
        {
            get
            {
                return _IsSuccess;
            }
            set
            {
                OnIsSuccessChanging(value);
                ReportPropertyChanging("IsSuccess");
                _IsSuccess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSuccess");
                OnIsSuccessChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSuccess;
        partial void OnIsSuccessChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSuccessChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Order 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="contentsWeight">ContentsWeight 属性的初始值。</param>
        /// <param name="toUserName">ToUserName 属性的初始值。</param>
        /// <param name="toUserPhone">ToUserPhone 属性的初始值。</param>
        /// <param name="toAddress">ToAddress 属性的初始值。</param>
        /// <param name="pickupTime">PickupTime 属性的初始值。</param>
        public static Order CreateOrder(global::System.Int64 id, global::System.String code, global::System.Double contentsWeight, global::System.String toUserName, global::System.String toUserPhone, global::System.String toAddress, global::System.DateTime pickupTime)
        {
            Order order = new Order();
            order.ID = id;
            order.Code = code;
            order.ContentsWeight = contentsWeight;
            order.ToUserName = toUserName;
            order.ToUserPhone = toUserPhone;
            order.ToAddress = toAddress;
            order.PickupTime = pickupTime;
            return order;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SrcUserName
        {
            get
            {
                return _SrcUserName;
            }
            set
            {
                OnSrcUserNameChanging(value);
                ReportPropertyChanging("SrcUserName");
                _SrcUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SrcUserName");
                OnSrcUserNameChanged();
            }
        }
        private global::System.String _SrcUserName;
        partial void OnSrcUserNameChanging(global::System.String value);
        partial void OnSrcUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SrcUserPhone
        {
            get
            {
                return _SrcUserPhone;
            }
            set
            {
                OnSrcUserPhoneChanging(value);
                ReportPropertyChanging("SrcUserPhone");
                _SrcUserPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SrcUserPhone");
                OnSrcUserPhoneChanged();
            }
        }
        private global::System.String _SrcUserPhone;
        partial void OnSrcUserPhoneChanging(global::System.String value);
        partial void OnSrcUserPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SrcAddress
        {
            get
            {
                return _SrcAddress;
            }
            set
            {
                OnSrcAddressChanging(value);
                ReportPropertyChanging("SrcAddress");
                _SrcAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SrcAddress");
                OnSrcAddressChanged();
            }
        }
        private global::System.String _SrcAddress;
        partial void OnSrcAddressChanging(global::System.String value);
        partial void OnSrcAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contents
        {
            get
            {
                return _Contents;
            }
            set
            {
                OnContentsChanging(value);
                ReportPropertyChanging("Contents");
                _Contents = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contents");
                OnContentsChanged();
            }
        }
        private global::System.String _Contents;
        partial void OnContentsChanging(global::System.String value);
        partial void OnContentsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ContentsWeight
        {
            get
            {
                return _ContentsWeight;
            }
            set
            {
                OnContentsWeightChanging(value);
                ReportPropertyChanging("ContentsWeight");
                _ContentsWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentsWeight");
                OnContentsWeightChanged();
            }
        }
        private global::System.Double _ContentsWeight;
        partial void OnContentsWeightChanging(global::System.Double value);
        partial void OnContentsWeightChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ContentsValue
        {
            get
            {
                return _ContentsValue;
            }
            set
            {
                OnContentsValueChanging(value);
                ReportPropertyChanging("ContentsValue");
                _ContentsValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentsValue");
                OnContentsValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _ContentsValue;
        partial void OnContentsValueChanging(Nullable<global::System.Decimal> value);
        partial void OnContentsValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToUserName
        {
            get
            {
                return _ToUserName;
            }
            set
            {
                OnToUserNameChanging(value);
                ReportPropertyChanging("ToUserName");
                _ToUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToUserName");
                OnToUserNameChanged();
            }
        }
        private global::System.String _ToUserName;
        partial void OnToUserNameChanging(global::System.String value);
        partial void OnToUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToUserPhone
        {
            get
            {
                return _ToUserPhone;
            }
            set
            {
                OnToUserPhoneChanging(value);
                ReportPropertyChanging("ToUserPhone");
                _ToUserPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToUserPhone");
                OnToUserPhoneChanged();
            }
        }
        private global::System.String _ToUserPhone;
        partial void OnToUserPhoneChanging(global::System.String value);
        partial void OnToUserPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToAddress
        {
            get
            {
                return _ToAddress;
            }
            set
            {
                OnToAddressChanging(value);
                ReportPropertyChanging("ToAddress");
                _ToAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToAddress");
                OnToAddressChanged();
            }
        }
        private global::System.String _ToAddress;
        partial void OnToAddressChanging(global::System.String value);
        partial void OnToAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Charges
        {
            get
            {
                return _Charges;
            }
            set
            {
                OnChargesChanging(value);
                ReportPropertyChanging("Charges");
                _Charges = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Charges");
                OnChargesChanged();
            }
        }
        private Nullable<global::System.Decimal> _Charges;
        partial void OnChargesChanging(Nullable<global::System.Decimal> value);
        partial void OnChargesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PickupTime
        {
            get
            {
                return _PickupTime;
            }
            set
            {
                OnPickupTimeChanging(value);
                ReportPropertyChanging("PickupTime");
                _PickupTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PickupTime");
                OnPickupTimeChanged();
            }
        }
        private global::System.DateTime _PickupTime;
        partial void OnPickupTimeChanging(global::System.DateTime value);
        partial void OnPickupTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SigninTime
        {
            get
            {
                return _SigninTime;
            }
            set
            {
                OnSigninTimeChanging(value);
                ReportPropertyChanging("SigninTime");
                _SigninTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SigninTime");
                OnSigninTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _SigninTime;
        partial void OnSigninTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnSigninTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="Storehouse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Storehouse : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Storehouse 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static Storehouse CreateStorehouse(global::System.Int64 id, global::System.String name)
        {
            Storehouse storehouse = new Storehouse();
            storehouse.ID = id;
            storehouse.Name = name;
            return storehouse;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Capacity
        {
            get
            {
                return _Capacity;
            }
            set
            {
                OnCapacityChanging(value);
                ReportPropertyChanging("Capacity");
                _Capacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Capacity");
                OnCapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _Capacity;
        partial void OnCapacityChanging(Nullable<global::System.Int32> value);
        partial void OnCapacityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Master
        {
            get
            {
                return _Master;
            }
            set
            {
                OnMasterChanging(value);
                ReportPropertyChanging("Master");
                _Master = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Master");
                OnMasterChanged();
            }
        }
        private global::System.String _Master;
        partial void OnMasterChanging(global::System.String value);
        partial void OnMasterChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        public static User CreateUser(global::System.Int64 id, global::System.String name, global::System.String password)
        {
            User user = new User();
            user.ID = id;
            user.Name = name;
            user.Password = password;
            return user;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AliasName
        {
            get
            {
                return _AliasName;
            }
            set
            {
                OnAliasNameChanging(value);
                ReportPropertyChanging("AliasName");
                _AliasName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AliasName");
                OnAliasNameChanged();
            }
        }
        private global::System.String _AliasName;
        partial void OnAliasNameChanging(global::System.String value);
        partial void OnAliasNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeCode
        {
            get
            {
                return _EmployeCode;
            }
            set
            {
                OnEmployeCodeChanging(value);
                ReportPropertyChanging("EmployeCode");
                _EmployeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeCode");
                OnEmployeCodeChanged();
            }
        }
        private global::System.String _EmployeCode;
        partial void OnEmployeCodeChanging(global::System.String value);
        partial void OnEmployeCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Enable;
        partial void OnEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnEnableChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastActivityDate;
        partial void OnLastActivityDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastActivityDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SOAWLDBModel", Name="Vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehicle : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Vehicle 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Vehicle CreateVehicle(global::System.Int64 id)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.ID = id;
            return vehicle;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LicensePlateNumber
        {
            get
            {
                return _LicensePlateNumber;
            }
            set
            {
                OnLicensePlateNumberChanging(value);
                ReportPropertyChanging("LicensePlateNumber");
                _LicensePlateNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LicensePlateNumber");
                OnLicensePlateNumberChanged();
            }
        }
        private global::System.String _LicensePlateNumber;
        partial void OnLicensePlateNumberChanging(global::System.String value);
        partial void OnLicensePlateNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WXCode
        {
            get
            {
                return _WXCode;
            }
            set
            {
                OnWXCodeChanging(value);
                ReportPropertyChanging("WXCode");
                _WXCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WXCode");
                OnWXCodeChanged();
            }
        }
        private global::System.String _WXCode;
        partial void OnWXCodeChanging(global::System.String value);
        partial void OnWXCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location_X
        {
            get
            {
                return _Location_X;
            }
            set
            {
                OnLocation_XChanging(value);
                ReportPropertyChanging("Location_X");
                _Location_X = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location_X");
                OnLocation_XChanged();
            }
        }
        private global::System.String _Location_X;
        partial void OnLocation_XChanging(global::System.String value);
        partial void OnLocation_XChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location_Y
        {
            get
            {
                return _Location_Y;
            }
            set
            {
                OnLocation_YChanging(value);
                ReportPropertyChanging("Location_Y");
                _Location_Y = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location_Y");
                OnLocation_YChanged();
            }
        }
        private global::System.String _Location_Y;
        partial void OnLocation_YChanging(global::System.String value);
        partial void OnLocation_YChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
