//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.WLIMS.Web.WCFService.Vehicle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/SOA.WLIMS.DAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Vehicle : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicensePlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicensePlateNumber {
            get {
                return this.LicensePlateNumberField;
            }
            set {
                this.LicensePlateNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.Vehicle.IServiceOf_Vehicle")]
    public interface IServiceOf_Vehicle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Vehicle/Add", ReplyAction="http://tempuri.org/IServiceOf_Vehicle/AddResponse")]
        bool Add(SOA.WLIMS.Web.WCFService.Vehicle.Vehicle model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Vehicle/Modify", ReplyAction="http://tempuri.org/IServiceOf_Vehicle/ModifyResponse")]
        bool Modify(SOA.WLIMS.Web.WCFService.Vehicle.Vehicle model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Vehicle/Delete", ReplyAction="http://tempuri.org/IServiceOf_Vehicle/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Vehicle/Get", ReplyAction="http://tempuri.org/IServiceOf_Vehicle/GetResponse")]
        SOA.WLIMS.Web.WCFService.Vehicle.Vehicle Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Vehicle/Query", ReplyAction="http://tempuri.org/IServiceOf_Vehicle/QueryResponse")]
        System.Collections.Generic.List<SOA.WLIMS.Web.WCFService.Vehicle.Vehicle> Query(SOA.WLIMS.Models.QueryParam para);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_VehicleChannel : SOA.WLIMS.Web.WCFService.Vehicle.IServiceOf_Vehicle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_VehicleClient : System.ServiceModel.ClientBase<SOA.WLIMS.Web.WCFService.Vehicle.IServiceOf_Vehicle>, SOA.WLIMS.Web.WCFService.Vehicle.IServiceOf_Vehicle {
        
        public ServiceOf_VehicleClient() {
        }
        
        public ServiceOf_VehicleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_VehicleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_VehicleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_VehicleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(SOA.WLIMS.Web.WCFService.Vehicle.Vehicle model) {
            return base.Channel.Add(model);
        }
        
        public bool Modify(SOA.WLIMS.Web.WCFService.Vehicle.Vehicle model) {
            return base.Channel.Modify(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public SOA.WLIMS.Web.WCFService.Vehicle.Vehicle Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Collections.Generic.List<SOA.WLIMS.Web.WCFService.Vehicle.Vehicle> Query(SOA.WLIMS.Models.QueryParam para) {
            return base.Channel.Query(para);
        }
    }
}
