//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.WLIMS.Web.WCFService.Store {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.Store.IServiceOf_Storehouse")]
    public interface IServiceOf_Storehouse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Storehouse/Add", ReplyAction="http://tempuri.org/IServiceOf_Storehouse/AddResponse")]
        bool Add(SOA.WLIMS.Service.DAL.Storehouse model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Storehouse/Modify", ReplyAction="http://tempuri.org/IServiceOf_Storehouse/ModifyResponse")]
        bool Modify(SOA.WLIMS.Service.DAL.Storehouse model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Storehouse/Delete", ReplyAction="http://tempuri.org/IServiceOf_Storehouse/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Storehouse/Get", ReplyAction="http://tempuri.org/IServiceOf_Storehouse/GetResponse")]
        SOA.WLIMS.Service.DAL.Storehouse Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Storehouse/Query", ReplyAction="http://tempuri.org/IServiceOf_Storehouse/QueryResponse")]
        System.Collections.Generic.List<SOA.WLIMS.Service.DAL.Storehouse> Query(SOA.WLIMS.Service.QueryParam para);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_StorehouseChannel : SOA.WLIMS.Web.WCFService.Store.IServiceOf_Storehouse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_StorehouseClient : System.ServiceModel.ClientBase<SOA.WLIMS.Web.WCFService.Store.IServiceOf_Storehouse>, SOA.WLIMS.Web.WCFService.Store.IServiceOf_Storehouse {
        
        public ServiceOf_StorehouseClient() {
        }
        
        public ServiceOf_StorehouseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_StorehouseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_StorehouseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_StorehouseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(SOA.WLIMS.Service.DAL.Storehouse model) {
            return base.Channel.Add(model);
        }
        
        public bool Modify(SOA.WLIMS.Service.DAL.Storehouse model) {
            return base.Channel.Modify(model);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public SOA.WLIMS.Service.DAL.Storehouse Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Collections.Generic.List<SOA.WLIMS.Service.DAL.Storehouse> Query(SOA.WLIMS.Service.QueryParam para) {
            return base.Channel.Query(para);
        }
    }
}
